### PR TITLE
feat(print): Adding html spaces

### PR DESCRIPTION
**Pull request by aemonge**
Included the HTML spaces so that we can indent easelly

### CODE REVIEW

**Comment by M1T0zd** [comment]
Hey, I just noticed your commit.

Could you give me a simple example on how this would be useful? Because I could it being similar in use to the `text.replace(/\t/g, "&emsp;");` line.

**Comment by aemonge** [comment]
Sure!

I'm a bit busy today, but I'll make time for it :)

**Comment by aemonge** [comment]
Okey..... so it didn't work 100%. 

But you got me wanted to help you, so I've made a new Pull Request; that allows rich-text characters such as: `\n\r` `\n` `<tab>` `<space>` to be interpreted literally by the browser natively (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre)

Hope it improves it :)

**Comment by M1T0zd** [comment]
Yes, the `<pre>`  tag. I just discovered it lately. It sounds like a waaay better solution. I will check out and test your new pull request later on!

I appreciate the effort ;)

**Pull request closed without merging**
