### PR TITLE
Use the <pre> html tag

### PR DESCRIPTION
**Pull request by aemonge**
Allows rich-text characters such as: \n\r \n <tab> <space> to be interpreted literally by the browser natively

### CODE REVIEW

**Comment by M1T0zd** [comment]
I've checked it out and the `<pre>` method works flawlessly! Awesome fix.

**Comment by M1T0zd** [comment]
What's up with the color changes though, you don't like it? ;P
I kinda like the over-the-top terminal feel more.

**Comment by aemonge** [comment]
Oh, lol. Yeah hehehe. I have my terminal with those same colors. The spirit is the same, we both want the terminal feel xD 
I can remove those changes no problem :)

**Comment by M1T0zd** [comment]
I'll undo it, no problem - keeping the pull simple. Though, it might an idea for the future to add some customizability. I'll get merge done ASAP!

**Comment by M1T0zd** [comment]
[use `&nbsp;`?](https://trello.com/c/1EfLIZxJ/22-use-nbsp)

**Pull request merged**
